// Generates glyphs.h from src/segments.js and the 5x7 font, so the panel's
// digits are the same geometry as the browser display rather than a redrawing
// of it. Run after changing either source:
//
//   node firmware/hub75/generate_glyphs.mjs
//
// Rasterises by testing each pixel centre against the real polygon, so what
// lands in the header is the quantisation the panel will actually show.
import { writeFileSync } from 'node:fs';
import { SEGMENTS, DIGIT_SEGMENTS } from '../../src/segments.js';
import { FONT, GLYPH_W, GLYPH_H, ADVANCE } from '../../tools/panel-preview/font5x7.mjs';

const DIGIT_W = 11, DIGIT_H = 20;
const VIEW_W = 100, VIEW_H = 180;
const ORDER = 'abcdefg';

const parse = (s) => s.split(' ').map((p) => p.split(',').map(Number));

function inside(poly, x, y) {
  let hit = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i], [xj, yj] = poly[j];
    if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) hit = !hit;
  }
  return hit;
}

// One uint16_t per row; bit 0 is the leftmost pixel.
function rasterise(name) {
  const poly = parse(SEGMENTS[name]);
  const rows = [];
  for (let j = 0; j < DIGIT_H; j++) {
    let bits = 0;
    for (let i = 0; i < DIGIT_W; i++) {
      const x = ((i + 0.5) / DIGIT_W) * VIEW_W;
      const y = ((j + 0.5) / DIGIT_H) * VIEW_H;
      if (inside(poly, x, y)) bits |= 1 << i;
    }
    rows.push(bits);
  }
  return rows;
}

const segRows = ORDER.split('').map(rasterise);
const lit = segRows.map((r) => r.reduce((n, b) => n + b.toString(2).split('1').length - 1, 0));

// Characters the board can show. The dash shown before any state arrives is
// defined here rather than in segments.js: the browser display has no use for
// one, and SevSeg synthesises its own, so this build is the only caller.
const EXTRA = { '-': 'g' };
const CHARS = ' -0123456789';
const masks = [...CHARS].map((ch) => {
  const segs = EXTRA[ch] ?? DIGIT_SEGMENTS[ch] ?? '';
  let m = 0;
  for (const s of segs) m |= 1 << ORDER.indexOf(s);
  return m;
});
if (!masks[CHARS.indexOf('-')]) throw new Error('dash glyph is empty');

const FONT_CHARS = ' !&-.0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const fontRows = [...FONT_CHARS].map((ch) => {
  const g = FONT[ch] ?? FONT[' '];
  return g.map((row) => [...row].reduce((b, c, i) => (c === '#' ? b | (1 << i) : b), 0));
});

const hex = (n, w) => `0x${n.toString(16).padStart(w, '0')}`;
const out = `// GENERATED by firmware/hub75/generate_glyphs.mjs — do not edit.
// Source: src/segments.js and tools/panel-preview/font5x7.mjs.
#pragma once

#include <stdint.h>

// Seven-segment digits, rasterised from the real polygons at ${DIGIT_W}x${DIGIT_H}.
// One uint16_t per row, bit 0 leftmost. Lit pixels per segment: ${lit.join(', ')}.
static const int GLYPH_DIGIT_W = ${DIGIT_W};
static const int GLYPH_DIGIT_H = ${DIGIT_H};
static const uint16_t GLYPH_SEGMENT[7][${DIGIT_H}] = {
${segRows.map((rows, i) => `  { ${rows.map((r) => hex(r, 4)).join(', ')} },  // ${ORDER[i]}`).join('\n')}
};

// Which segments each character lights, indexed by GLYPH_CHARS.
static const char GLYPH_CHARS[] = "${CHARS}";
static const uint8_t GLYPH_MASK[] = { ${masks.map((m) => hex(m, 2)).join(', ')} };

// 5x7 bitmap font. One uint8_t per row, bit 0 leftmost.
static const int FONT_W = ${GLYPH_W};
static const int FONT_H = ${GLYPH_H};
static const int FONT_ADVANCE = ${ADVANCE};
static const char FONT_CHARS[] = "${FONT_CHARS.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}";
static const uint8_t FONT_ROWS[][${GLYPH_H}] = {
${fontRows.map((rows, i) => `  { ${rows.map((r) => hex(r, 2)).join(', ')} },  // ${FONT_CHARS[i] === ' ' ? 'space' : FONT_CHARS[i]}`).join('\n')}
};

inline int glyphIndex(char c) {
  for (int i = 0; GLYPH_CHARS[i]; i++) if (GLYPH_CHARS[i] == c) return i;
  return 0;
}

inline int fontIndex(char c) {
  if (c >= 'a' && c <= 'z') c = char(c - 'a' + 'A');
  for (int i = 0; FONT_CHARS[i]; i++) if (FONT_CHARS[i] == c) return i;
  return 0;
}
`;

writeFileSync(new URL('./glyphs.h', import.meta.url), out);
console.log(`glyphs.h: 7 segments at ${DIGIT_W}x${DIGIT_H}, ` +
  `${CHARS.length} digit masks, ${FONT_CHARS.length} font glyphs`);
